apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: charts/kyverno/kyverno-v2.6.0.tgz
      version: "2.6.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1m