apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: policies-values
    behavior: replace
    files:
      - values.yaml=policies-values.yaml
patchesStrategicMerge:
  - policies-release-patch.yaml