apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policies
  namespace: security-policies
spec:
  releaseName: security-kyverno-policies
  chart:
    spec:
      chart: security-kyverno-policies
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: policies
        namespace: flux-system
  interval: 1m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: policies-values